/** Listado curado de clubes organizadores AEP (nombre + e-mail de devolución). */
export const AEP_CLUBS_CURATED: ReadonlyArray<{ name: string; email: string }> = [
  { name: "KOOK VERA Almeria", email: "kooklevantamientosdepotencia@gmail.com" },
  { name: "DEPORNIXAR ALMERÍA", email: "dhernandezfer@gmail.com" },
  { name: "ALMERÍA BARBELL CLUB", email: "powerliftingalmeria@gmail.com" },
  { name: "EFFICIENT STRENGTH Almeria", email: "efficientstrengthclub@gmail.com" },
  { name: "POWER HUERCAL-OVERA", email: "cdpowerho@gmail.com" },
  { name: "POWERLIFTING CHIPIONA", email: "powerliftingchipiona@gmail.com" },
  { name: "BASIC STRENGTH Cádiz", email: "jaimecortesheredia@gmail.com" },
  { name: "NAMEK BARBELL CLUB Cádiz", email: "alemail@gmail.com" },
  { name: "RESTLESS CLUB Cadiz", email: "restlessclubpowerlifting@gmail.com" },
  { name: "GOAT POWER CLUB Córdoba", email: "goatpowerclub@gmail.com" },
  { name: "POWERLIFTING LIFTERS Córdoba", email: "alfonsobonillagranados@gmail.com" },
  { name: "FUERZA NAZARI Granada", email: "cdfuerzanazari@gmail.com" },
  { name: "LIFT AMBITION Granada", email: "liftambition20@gmail.com" },
  { name: "MOUNTAIN STRENGTH Granada", email: "quirantedavid01@gmail.com" },
  { name: "THE PRMODE Granada", email: "merchandisingtheprmode@gmail.com" },
  { name: "PEPE POWER TEAM Granada", email: "pptclubpowerlifting@gmail.com" },
  { name: "ALTERNATIVE RAW Huelva", email: "almonterawpowerlifgting@gmail.com" },
  { name: "RV STRENGTH Huelva", email: "rvstrengthcoaching@gmail.com" },
  { name: "POWERLIFTING ANDUJAR", email: "powerliftingandujar@gmail.com" },
  { name: "POWERLIFTING JAEN", email: "cdpowerliftingjaen@gmail.com" },
  { name: "POWER RANGERS STRENGTH Jaén", email: "powerrangersstrength@gmail.com" },
  { name: "ENERGY ALHAURÍN", email: "cdenergyalh@gmail.com" },
  { name: "FG POWER ALHAURÍN", email: "fgpersonaltrainermlg@gmail.com" },
  { name: "84 POWERLIFTING TEAM Malaga", email: "84powerliftingteam@gmail.com" },
  { name: "MÁLAGA POWER TEAM", email: "malagapowerteam@gmail.com" },
  { name: "PROJECT STRENGTH Málaga", email: "adrich7ko@gmail.com" },
  { name: "POWERLIFTING MARBELLA", email: "powerliftingmarbella@gmail.com" },
  { name: "VELIFT STRENGTH Málaga", email: "halterofiliamalaga@gmail.com" },
  { name: "FUERZA GUADAIRA", email: "cdfuerzaguadaira@gmail.com" },
  { name: "ÉLITE BOLLULLOS", email: "clubelitepowerlifting@gmail.com" },
  { name: "ELITE POWERHOUSE Sevilla", email: "clubelitepowerhouse@gmail.com" },
  { name: "IRONSIDE STRENGTH Sevilla", email: "rafael@gnoguer.com" },
  { name: "GORILAS POWER TEAM Sevilla", email: "gorillaspowerteam@gmail.com" },
  { name: "POWERLIFTING SEVILLA", email: "powerliftingsevilla@gmail.com" },
  { name: "DU&QUE SPORT GYM CLUB Sevilla", email: "tokipaferrari46@hotmail.com" },
  { name: "SOUTH POWER Sevilla", email: "southpowerstrength@gmail.com" },
  { name: "ATLETAS DE FUERZA CASARICHE Sevilla", email: "pedromoriana2017@gmail.com" },
  { name: "BARBASTRO POWERLIFTING Huesca", email: "cfbpowerlifting@gmail.com" },
  { name: "ZARAGOZA BARBELL", email: "aragonbarbell@gmail.com" },
  { name: "TEAM CE POWERLIFTING Zaragoza", email: "cembid.team@gmail.com" },
  { name: "ZEUS Huesca", email: "santigg1986@gmail.com" },
  { name: "GRIND TEAM GIJON", email: "grindteamgijon@gmail.com" },
  { name: "ASOCIACIÓN ASTURIANA", email: "a.a.depowerlifting@gmail.com" },
  { name: "VETUSTA POWERLIFTING Asturias", email: "vetustapowerlifting@gmail.com" },
  { name: "CONQUER POWER CLUB Oviedo", email: "info@conquerfitclub.es" },
  { name: "WORKER POWER Asturias", email: "workerpowersasturias@gmail.com" },
  { name: "CONRA CLUB DE FORÇA Mallorca", email: "conragym@gmail.com" },
  { name: "FUERZA KB Baleares", email: "lauraperaltacabrera@gmail.com" },
  { name: "CIUTAT DE PALMA", email: "powerliftingciutatdepalma@gmail.com" },
  { name: "ASOCIACION IRON LIFTERS POWERLIFTIN", email: "clubdeportivoironlifters@gmail.com" },
  { name: "POWERLIFTING IBIZA", email: "clubpowerliftingibiza@gmail.com" },
  { name: "MENTALIFT JJ STERNGTH CLUB Baleares", email: "catalinainfo11@gmail.com" },
  { name: "DISCIPLINE Málaga", email: "disciplinepowerlifting@gmail.com" },
  { name: "ELITE CANARIAS", email: "elitcanarias@gmail.com" },
  { name: "PEGASUS POWERLIFTING Canarias", email: "pegasuspowerlifting@hotmail.com" },
  { name: "WAVES Canarias", email: "wavesgcgym@gmail.com" },
  { name: "CANARY STRENGTH", email: "canarystrengthclub@gmail.com" },
  { name: "TIGOT POWERLIFTING Canarias", email: "tigotpowerlifting@gmail.com" },
  { name: "FUERZA GUANCHE Canarias", email: "fuerzaguanchemail@gmail.com" },
  { name: "URUZ STRENGTH Canarias", email: "uruzstrengthteam@gmail.com" },
  { name: "IRON POWER TENERIFE", email: "ironbox.jf@gmail.com" },
  { name: "TEAM ELITETRAINER Cantabria", email: "teamelitetrainerpowerlifting@gmail.com" },
  { name: "POWERLIFTING CANTABRIA", email: "cristianserna6@gmail.com" },
  { name: "YOUNG AMBITION Cantabria", email: "youngambitioncantabria@gmail.com" },
  { name: "POWERLIFTING ALBACETE", email: "powerliftingalbacete@gmail.com" },
  { name: "ECLIPSE POWERLIFTING Ciudad Real", email: "eclipsepowerclub@gmail.com" },
  { name: "INSANE POWERLIFTING CIUDAD REAL", email: "ipower.strength@gmail.com" },
  { name: "SOHO WEIGHTLIFTING Ciudad Real", email: "secretaria@vitalgroupfn.com" },
  { name: "ZB BARBELL Ciudad Real", email: "zbbarbell@gmail.com" },
  { name: "BARRAS COLGADAS STRENGTH Cuenca", email: "barrascolgadasstrengthsociety@gmail.com" },
  { name: "BELIAL POWERLIFTING Toledo", email: "belialpowerlifting@gmail.com" },
  { name: "BERSERKERS Toledo", email: "oscarsanchez.pt@hotmail.com" },
  { name: "POWERLIFTING TOLEDO", email: "powerliftingtoledo@gmail.com" },
  { name: "ASTERION BULLS Toledo", email: "asterion.bulls@gmail.com" },
  { name: "RS LIFTING Ávila", email: "rslifting.av@gmail.com" },
  { name: "CELTIBERIAN LIFTERS Burgos", email: "celtiberianlifters@gmail.com" },
  { name: "STRENGTH BURGOS", email: "strengthburgos@gmail.com" },
  { name: "FUERZA NORTE León", email: "powerlifting.fuerzanorte@gmail.com" },
  { name: "POWERLIFTING SALAMANCA", email: "powerliftingsalamanca@gmail.com" },
  { name: "POWERLIFTING NUMANCIA", email: "power.numancia@gmail.com" },
  { name: "ASENSIO POWERLIFTING Valladolid", email: "clubasensiopowerlifting@gmail.com" },
  { name: "VALKYRIA PT Valladolid", email: "valkyriapt@gmail.com" },
  { name: "FEDERACIÓN CATALANA", email: "info@fc-culturisme.cat" },
  { name: "FRENETIK POWERLIFTING Barcelona", email: "frenetikpowerliftingclub@gmail.com" },
  { name: "OLYMPIA BARCELONA", email: "pautoro20@hotmail.com" },
  { name: "POWERLIFTING BARCELONA", email: "barcelonapowerlifting@gmail.com" },
  { name: "RIVAL POWERLIFTING Barcelona", email: "afiliacionesrivalclub@gmail.com" },
  { name: "THE NEW ERA TEAM Barcelona", email: "newera.trainers@gmail.com" },
  { name: "PBP CLUB Barcelona", email: "clubpbp@gmail.com" },
  { name: "ATENEA POWERLIFTING Barcelona", email: "ateneapowerlifting@gmail.com" },
  { name: "UNDERGROUND LIFTING Barcelona", email: "themajorcoaching@gmail.com" },
  { name: "MOONSTONE BARBELL Sabadell", email: "moonstonebarbell@gmail.com" },
  { name: "RZ POWER TEAM Sabadell", email: "antoni-10-23@hotmail.com" },
  { name: "FORÇA LAIESKEN Barcelona", email: "clubfuerzalaiesken@gmail.com" },
  { name: "STB STRENGTH Barcelona", email: "danilandeira.datapower@gmail.com" },
  { name: "FORÇA VILLAFRANCA", email: "clubdeforcavilafranca@gmail.com" },
  { name: "VOLCANO STRENGTH Girona", email: "volcanstrengthclub@gmail.com" },
  { name: "STRENGTH LEGACY Lleida", email: "victorlg98@hotmail.com" },
  { name: "UNITY FORCE Tarragona", email: "unityforcepowerlifting@gmail.com" },
  { name: "PRAETORIANS Tarragona", email: "praetorianstgn@gmail.com" },
  { name: "GNO TEAM Tarragona", email: "osckygnoroc@gmail.com" },
  { name: "ERASO POWERLIFTING Alava", email: "erasopwr@gmail.com" },
  { name: "HIRUGORRI POWERLIFTING Arava", email: "hirugorripowerlifting@gmail.com" },
  { name: "RAW BARBELL CLUB Bizkaia", email: "barbellclubraw@gmail.com" },
  { name: "IRON HELL Bizkaia", email: "ironhellbizkaia@gmail.com" },
  { name: "RAW RAGE POWERLIFTING Bizkaia", email: "rawragepowerlifting@gmail.com" },
  { name: "IZARRA POWERLIFTING Bizkaia", email: "izarrapowerkluba@gmail.com" },
  { name: "STRONG POWER Bilbao", email: "strongainho@gmail.com" },
  { name: "GOIERRI KE Gipuzkoa", email: "goierripower@gmail.com" },
  { name: "ZARAUTZ BURDIN ZALEAK Gipuzkoa", email: "zarautzbasqueforge@gmail.com" },
  { name: "POWER PRIME Bilbao", email: "clubfuerzaprime@gmail.com" },
  { name: "NORBA POWER Cáceres", email: "cjcorporation20@gmail.com" },
  { name: "POWERLIFTING EXTREMADURA", email: "powerliftingextremadura@gmail.com" },
  { name: "BEÖRN POWERLIFTING Coruña", email: "beornpowerlifting@gmail.com" },
  { name: "FÉNIX GALICIA POWER", email: "jronkol@hotmail.com" },
  { name: "ONI BARBELL Coruña", email: "onibarbellclubgalicia@gmail.com" },
  { name: "720 POWERLIFTING OURENSE", email: "720powerlifting@gmail.com" },
  { name: "VÁKNER POWERLIFTING GALIZA", email: "vaknerpowerliftinggaliza@gmail.com" },
  { name: "GIM VITAL Pontevedra", email: "activeservice15@outlook.com" },
  { name: "GALILIFTERS Pontevedra", email: "galilifters2021@gmail.com" },
  { name: "STRENGTH PHASE Madrid", email: "e.galhardo66@gmail.com" },
  { name: "RISING POWER Madrid", email: "risingpowercenter@gmail.com" },
  { name: "FUERZA LA FORJA Alcala de Henares", email: "munozhiguerasraul@gmail.com" },
  { name: "SPECIFIC STRENGTH Madrid", email: "specificstrengthmadrid@gmail.com" },
  { name: "VENDETTA POWERLIFTING Madrid", email: "vendettapowerlifting@gmail.com" },
  { name: "IRONBORN Madrid", email: "strengthironborn@gmail.com" },
  { name: "BLACKBARBELL Madrid", email: "blackbarbellclubpowerlifting@gmail.com" },
  { name: "VILLA POWERLIFTING Madrid", email: "victordelavillasan@gmail.com" },
  { name: "PUERTA DE LA SIERRA Madrid", email: "mmendozabu@gmail.com" },
  { name: "MIKEBARBELL Madrid", email: "mikebarbell.coach@gmail.com" },
  { name: "IRON POWER Fuenlabrada", email: "cdironpower@gmail.com" },
  { name: "SOUTHWEST POWERLIFTING Madrid", email: "southpowerstrength@gmail.com" },
  { name: "EDUARDO RALLO Madrid", email: "eduardoralloentrenamiento@gmail.com" },
  { name: "INTEND POWER Madrid", email: "intendpower@gmail.com" },
  { name: "AG STRENGTH Madrid", email: "agstrengthclub@gmail.com" },
  { name: "ALFA Forjando Atletas Madrid", email: "info@forjandoatletas.es" },
  { name: "ATPOWER TEAM Madrid", email: "atpowerteammadrid@gmail.com" },
  { name: "CROM GYM Madrid", email: "cromgympower@gmail.com" },
  { name: "DANIGPOWER Madrid", email: "clubdanigpower@gmail.com" },
  { name: "DT POWER Madrid", email: "dtfitnessmadrid@gmail.com" },
  { name: "ENTRENA INTENSO Madrid", email: "rauloon@hotmail.com" },
  { name: "ÉXITO28 Madrid", email: "exito28madrid@gmail.com" },
  { name: "FENRIR Madrid", email: "fenrir.powerclub@gmail.com" },
  { name: "GRANDA Madrid", email: "grandapwr@gmail.com" },
  { name: "HERU POWERLIFTING Madrid", email: "heru.powerlifting.023@gmail.com" },
  { name: "LEVANTAMIENTO Madrid", email: "clublpmpower@gmail.com" },
  { name: "MAD POWERLIFTING Madrid", email: "madpowerlifting28100@gmail.com" },
  { name: "MGF POWER TEAM Madrid", email: "mariogracia2000@gmail.com" },
  { name: "POWERLIFTING MADRID", email: "info@clubpowerliftingmadrid.com" },
  { name: "RAGNAROK Madrid", email: "club.powerlifting.ragnarok@gmail.com" },
  { name: "SIDEROPOLIS Madrid", email: "club@sideropolis.es" },
  { name: "SILENT CLUB Madrid", email: "silentcrew00@hotmail.com" },
  { name: "SOY POWERLIFTER Madrid", email: "ignaciofernandezverdugo@gmail.com" },
  { name: "STRENGTH CAPITAL Madrid", email: "strengthcapitalteam@gmail.com" },
  { name: "SUNDAY POWER Madrid", email: "clubsundaypower@gmail.com" },
  { name: "ALFA FUERZA Y ARCO CDE Madrid", email: "fuerzayarco@gmail.com" },
  { name: "OVERSIZE STRENGT CLUB Madrid", email: "adri-japa@hotmail.com" },
  { name: "POWER VALHALLA Madrid", email: "powervalhallasc@gmail.com" },
  { name: "BLACK CROWN POWERLIFTING Madrid", email: "blackcrownpower@gmail.com" },
  { name: "LEONES HAKEÑOS Madrid", email: "pablo.gutierrezm96@gmail.com" },
  { name: "HOME AND HEATLH FITNESS Madrid", email: "info@homeandhealthfitness.com" },
  { name: "ABLAZE STRENGTH Madrid", email: "strengthablaze@gmail.com" },
  { name: "WORK & FAITH Madrid", email: "workandfaithteam@gmail.com" },
  { name: "BANZAI STRENGTH CARTAGENA", email: "banzai.strength@gmail.com" },
  { name: "MONTOCÁN CEUTÍ", email: "rubios8@hotmail.com" },
  { name: "MYRTEA LIFTING CLUB Murcia", email: "myrtealiftingclub@gmail.com" },
  { name: "SPARTA Murcia", email: "clubspartamurcia@gmail.com" },
  { name: "POWER HOUSE Pamplona", email: "xthorpowerlifting@gmail.com" },
  { name: "POWERLIFTING NAVARRA", email: "powerliftingnavarra@gmail.com" },
  { name: "FLOWERLIFTING CLUB Alicante", email: "flowerliftingclub@gmail.com" },
  { name: "ALTEA-FINESTRAT-L'ALFÀS", email: "gpamadeo@gmail.com" },
  { name: "IRON TEAM Elche", email: "ironteampower@gmail.com" },
  { name: "BEGOAL Alicante", email: "powerlifting.centrobegoal@gmail.com" },
  { name: "POWER SAN VICENTE", email: "clubpowersanvicente@gmail.com" },
  { name: "POWER AMIBI Alicante", email: "powerliftingibi@gmail.com" },
  { name: "ANVIL STRENGTH Valencia", email: "anvilstrengthclub@gmail.com" },
  { name: "ELITE LIFTERS Valencia", email: "fuerzagimnasio@gmail.com" },
  { name: "FUERZA ISABEL ATLAS Chiva", email: "clubfuerzaisabel@gmail.com" },
  { name: "KRAKEN STRENGTH Lliria", email: "krakenstrengthclub@gmail.com" },
  { name: "GR STRENGTH ALMUSSAFES Valencia", email: "contactogr8@gmail.com" },
] as const;
