import * as admin from "./memory-admin";
import * as analytics from "./memory-analytics";
import * as competitions from "./memory-competitions";
import * as referees from "./memory-referees";
import { memoryCompensationService } from "./memory-compensation";

export const memoryDataService = {
  getMeta: referees.getMeta,
  getDashboard: competitions.getDashboard,
  getReferees: referees.getReferees,
  getReferee: referees.getReferee,
  createReferee: referees.createReferee,
  updateReferee: referees.updateReferee,
  deleteReferee: referees.deleteReferee,
  getJudgeProfile: (refereeId: string) =>
    referees.getJudgeProfile(
      refereeId,
      (id) => admin.getExams(id),
      (id) => admin.getReports(id),
    ),
  listRefereeSanctions: referees.listRefereeSanctions,
  getActiveSanction: (refereeId: string) =>
    referees.getActiveSanction(refereeId, referees.listRefereeSanctions),
  createRefereeSanction: admin.createRefereeSanction,
  revokeRefereeSanction: admin.revokeRefereeSanction,
  markSanctionDelegateNotified: admin.markSanctionDelegateNotified,
  getSanctionAlerts: admin.getSanctionAlerts,
  expireStaleSanctions: admin.expireStaleSanctions,

  getCompetitions: competitions.getCompetitions,
  getCompetitionOptions: competitions.getCompetitionOptions,
  getCompetition: competitions.getCompetition,
  createCompetition: competitions.createCompetition,
  updateCompetition: competitions.updateCompetition,
  deleteCompetition: competitions.deleteCompetition,
  getCompetitionAvailability: admin.getCompetitionAvailability,
  addCompetitionAvailability: admin.addCompetitionAvailability,
  removeCompetitionAvailability: admin.removeCompetitionAvailability,
  findCompetitionDuplicates: competitions.findCompetitionDuplicates,
  removeDuplicateCompetitions: competitions.removeDuplicateCompetitions,

  getRoster: competitions.getRoster,
  saveCompetitionTemplate: competitions.saveCompetitionTemplate,
  setSlotFlags: competitions.setSlotFlags,
  validateAssign: competitions.validateAssign,
  assignReferee: competitions.assignReferee,
  clearSlot: competitions.clearSlot,
  clearRosterAssignments: competitions.clearRosterAssignments,
  submitRoster: competitions.submitRoster,
  unlockRosterImprevisto: competitions.unlockImprevisto,
  saveDraft: competitions.saveDraft,
  getApprovals: competitions.getApprovals,
  reviewApproval: competitions.reviewApproval,
  getRosterHistory: competitions.getRosterHistory,
  exportRoster: competitions.exportRoster,
  getNavCounts: analytics.getNavCounts,

  getRegulations: admin.getRegulations,
  getAnalytics: analytics.getAnalytics,
  getPromotions: admin.getPromotions,
  reviewPromotion: admin.reviewPromotion,
  createPromotion: admin.createPromotion,
  getExams: admin.getExams,
  createExam: admin.createExam,
  updateExam: admin.updateExam,
  deleteExam: admin.deleteExam,
  getReport: admin.getReport,
  getReports: admin.getReports,
  createReport: admin.createReport,
  updateReport: admin.updateReport,
  deleteReport: admin.deleteReport,
  importJudgesRegistry: admin.importJudgesRegistry,

  getCompensationSummary: memoryCompensationService.getSummary,
  recalculateCompensation: memoryCompensationService.recalculate,
  updateCompensationClaim: memoryCompensationService.updateClaim,
  calculateCompensationDistance: memoryCompensationService.calculateDistance,
  calculateAllCompensationDistances: memoryCompensationService.calculateAllDistances,
  getCompensationClaimForExport: memoryCompensationService.getClaimForExport,
  getCompensationHub: memoryCompensationService.getHub,
};
